[build]
  command = "cd page && npm install && npm run build"
  publish = "dist"
  functions = "../functions"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
