[build]
  command = "mkdir -p static"
  publish = "static" # A dummy directory, as this is a backend service

[functions]
  included_files = ["app/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
